WebMVC/Controllers/CartController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using WebMVC.Entity;
using WebMVC.Models;

namespace WebMVC.Controllers
{
    public class CartController : Controller
    {
        public IActionResult Add(string name)
        {
            ViewData["username"] = HttpContext.Session.GetString("username");
            string quantity = HttpContext.Session.GetString(name);
            // if not buy 
            if(quantity == null)
            {
                quantity = "1";
                HttpContext.Session.SetString(name, quantity);
            }
            else
            {
                HttpContext.Session.SetString(name, (Convert.ToInt32(quantity) + 1).ToString());
            }
            return Redirect("/Customer/Index");
        }

        public IActionResult Show()
        {
            ViewData["username"] = HttpContext.Session.GetString("username");
            Dictionary<string, int> dic = new Dictionary<string, int>();
            // get all product
            List<Product> list = new DAOProduct().GetAllProduct();
            // loop for traverse all product
            foreach (Product product in list)
            {                               
                string quantity = HttpContext.Session.GetString(product.ProductName.Trim());
                // if user bought product
                if (quantity != null)
                {
                    dic.Add(product.ProductName, Convert.ToInt32(quantity));
                }
                
            }
            return View(dic);
        }
        public IActionResult Update(string name , int quantity)
        {
            HttpContext.Session.SetString(name, quantity.ToString());
            return RedirectToAction("Show");
        }

        public IActionResult Remove(string name)
        {
            HttpContext.Session.Remove(name);
            return RedirectToAction("Show");
        }

        // check list cart empty
        public bool CheckListCartEmpty()
        {
            int count = 0;
            // get all product
            List<Product> list = new DAOProduct().GetAllProduct();
            // loop for traverse all product
            foreach (Product product in list)
            {
                string quantity = HttpContext.Session.GetString(product.ProductName.Trim());
                // if user bought product
                if (quantity != null)
                {
                    count++;
                }
            }
            return count == 0;
        }
        public IActionResult CheckOut()
        {
            ViewData["username"] = HttpContext.Session.GetString("username");
            // if list cart empty
            if (CheckListCartEmpty())
            {
                ViewData["message"] = "You can't check out when your cart is empty";
                Dictionary<string, int> dic = new Dictionary<string, int>();
                return View("Views/Cart/Show.cshtml" ,dic);
            }
            else
            {
                Dictionary<string, int> dic = new Dictionary<string, int>();
                // get all product
                List<Product> list = new DAOProduct().GetAllProduct();
                // loop for traverse all product
                foreach (Product product in list)
                {
                    string quantity = HttpContext.Session.GetString(product.ProductName.Trim());
                    // if user bought product
                    if (quantity != null)
                    {
                        dic.Add(product.ProductName, Convert.ToInt32(quantity));
                    }
                }
                return View(dic);
            }
            
        }
        [HttpPost]
        public IActionResult DoCheckOut(int sum , string address)
        {
            ViewData["username"] = HttpContext.Session.GetString("username");
            DateTime dateTime = DateTime.Now;
            string date = dateTime.ToString("yyyy-MM-dd");
            string username = ViewData["username"].ToString();
            int ID = new DAOCustomer().getCustomerID(username);
            Order order = new Order()
            {
                CustomerID = ID,
                status = "New",
                TotalPrice = sum,
                OrderDate = date,
                ShipID = null,
                ShippedDate = null,
                Address = address              
            };
            int numberOrder = new DAOOrder().AddOrder(order);
            int orderID = new DAOOrder().getOrderID();
            int detailID = 1;
            Dictionary<string, int> dic = new Dictionary<string, int>();
            // get all product
            List<Product> list = new DAOProduct().GetAllProduct();
            // loop for traverse all product
            foreach (Product product in list)
            {
                string quantity = HttpContext.Session.GetString(product.ProductName.Trim());
                // if user bought product
                if (quantity != null)
                {
                    dic.Add(product.ProductName, Convert.ToInt32(quantity));
                }
            }
            // loop for traverse through all dic
            foreach(string name in dic.Keys)
            {
                int quantity = dic[name];
                int productID = new DAOProduct().getProductID(name);
                int price = new DAOProduct().getPrice(name);
                OrderDetail detail = new OrderDetail()
                {
                     OrderID = orderID,
                     DetailID = detailID,
                     ProductID = productID,
                     Price = price,
                     Quantity = quantity
                };
                int numberDetail = new DAOOrderDetail().AddOrderDetail(detail);
                detailID++;
            }
            // loop for traverse all product
            foreach (Product product in list)
            {
                HttpContext.Session.Remove(product.ProductName.Trim());
            }
            ViewData["address"] = address;
            ViewData["message"] = "Check out successful";
            return View("Views/Cart/CheckOut.cshtml",dic);
        }

    }
}

WebMVC/Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Models;

namespace WebMVC.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Show()
        {
            return View();
        }
        [HttpPost]
        public IActionResult DoLogin(string username , string password)
        {
            // if account valid
            if(new DAOAccount().CheckAccountValid(username, password))
            {
                bool IsBlocked = new DAOAccount().getIsBlocked(username);
                // if account is blocked
                if (IsBlocked)
                {
                    ViewData["message"] = "Your account has been blocked";
                    return View("Views/Login/Show.cshtml");
                }
                else
                {
                    HttpContext.Session.SetString("username",username);
                    string role = new DAOAccount().getRoleName(username);
                    //if role is customer
                    if (role.Equals("Customer"))
                    {
                        return Redirect("/Customer/Index");
                    // if role is shipper
                    }else if (role.Equals("Shipper"))
                    {
                        return Redirect("/Shipper/Index");
                    }
                    else
                    {
                        return Redirect("/Admin/Index");
                    }
                }
            }
            else
            {
                ViewData["message"] = "Username or password incorrect";
                return View("Views/Login/Show.cshtml");
            }
        }
    }
}

WebMVC/Controllers/LogoutController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebMVC.Controllers
{
    public class LogoutController : Controller
    {
        public IActionResult Index()
        {
            HttpContext.Session.Clear();
            return Redirect("/Home/Index");
        }
    }
}

WebMVC/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;
using WebMVC.Entity;
using WebMVC.Models;
namespace WebMVC.Controllers
{
    public class ProfileController : Controller
    {
        public IActionResult Show()
        {
            ViewData["username"] = HttpContext.Session.GetString("username");
            string username = ViewData["username"].ToString();
            string role = new DAOAccount().getRoleName(username);
            // if role is customer
            if (role.Equals("Customer"))
            {
                Customer customer = new DAOCustomer().getProfile(username);
                return View("Views/Profile/Customer.cshtml", customer);
            }
            else
            {
                Shipper shipper = new DAOShipper().getProfile(username);
                return View("Views/Profile/Shipper.cshtml", shipper);
            }
        }
        public IActionResult Update(string fullName , int gender ,string phone , string email)
        {
            ViewData["username"] = HttpContext.Session.GetString("username");
            string username = ViewData["username"].ToString();
            string role = new DAOAccount().getRoleName(username); 
            // if customer
            if (role.Equals("Customer"))
            {
               Customer customer =new Customer()
               {
                FullName = fullName,
                Gender = gender == 1 ?true :false,
                Phone = phone,
                Email = email,
                Username = username
                };
                Regex regex = new Regex("^[0-9]+$");
                // if phone invalid
                if (!regex.IsMatch(phone) || phone.Length != 10)
                {
                    ViewData["message"] = "Phone only number and length is 10";
                    return View("Views/Profile/Customer.cshtml" , customer);
                }
                else
                {
                    int number = new DAOCustomer().UpdateCustomer(customer);
                    // if update successful
                    if(number > 0)
                    {
                        ViewData["mess"] = "Change successful";
                        return View("Views/Profile/Customer.cshtml", customer);
                    }
                }
            }
            else
            {
                Shipper shipper = new Shipper()
                {
                    FullName = fullName,
                    Gender = gender == 1 ? true : false,
                    Phone = phone,
                    Email = email,
                    Username = username
                };
                Regex regex = new Regex("^[0-9]+$");
                // if phone invalid
                if (!regex.IsMatch(phone) || phone.Length != 10)
                {
                    ViewData["message"] = "Phone only number and length is 10";
                    return View("Views/Profile/Shipper.cshtml", shipper);
                }
                else
                {
                    int number = new DAOShipper().UpdateShipper(shipper);
                    // if update successful
                    if (number > 0)
                    {
                        ViewData["mess"] = "Change successful";
                        return View("Views/Profile/Shipper.cshtml", shipper);
                    }
                }
            }
            return null;
        }

    }
}

WebMVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PHONESHOP | E-commerce template</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @{
                    // if not login
                    if(ViewData["username"] == null)
                    {
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    }
                    else
                    {
                        string username = ViewData["username"].ToString();
                        string role = new DAOAccount().getRoleName(username);
                        <a class="navbar-brand" asp-area="" asp-controller="@role" asp-action="Index">Home</a>
                    }
                }
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">     
                      @{
                                // if not login
                                if(ViewData["username"] == null )
                                {
                                <li class="nav-item">  <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Show">Login</a> </li>
                            }
                            else

                            {
                                string username = ViewData["username"].ToString();
                                string role = new DAOAccount().getRoleName(username);
                                // if role is customer
                                if (role.Equals("Customer"))
                                {
                                  <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Show">Cart</a></li>
                                   <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="Show">Welcome @ViewData["username"].ToString()</a></li>
                                    <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Logout" asp-action="Index">Logout</a></li>
                                    // if role is shipper
                                }else if (role.Equals("Shipper"))
                                {
                                    <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="Show">Welcome @ViewData["username"].ToString()</a></li>
                                    <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Logout" asp-action="Index">Logout</a></li>
                                }
                                else
                                {
                                    <li class="nav-item"><a class="nav-link text-dark" href="#">Welcome admin</a></li>
                                    <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Logout" asp-action="Index">Logout</a></li>
                                }

                                    
                                }

                                }
                            
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @{
        // if not login
        if(ViewData["username"] == null)
        {
            <footer class="border-top footer text-muted">
                <div class="container">
                    &copy; 2022 - WebMVC - <a href="#">Duc</a>
                </div>
            </footer>
        }
        else
        {
            string username = ViewData["username"].ToString();
            string role = new DAOAccount().getRoleName(username);
            //if role not admin
            if (!role.Equals("Admin"))
            {
               <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebMVC - <a href="#">Duc</a>
        </div>
    </footer>  
            }
        }
    }
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>